### ISSUE TITLE
Transfer bazel-gazelle to bazel-contrib

### ISSUE THREAD

**Issue by meteorcloudy** [bazel-contrib/bazel-gazelle#1924]
**Description:**

This issue proposes transferring the bazel-gazelle repository from the `bazelbuild` GitHub organization to the `bazel-contrib` GitHub organization, which is owned by the [Community for Bazel](https://github.com/bazel-contrib/.github/blob/master/Community%20for%20Bazel%20Technical%20Charter.pdf) project under the Linux Foundation.

**GitHub Discussion:** https://github.com/orgs/bazelbuild/discussions/2

**Impacts:**

* GitHub issues & PRs will be transferred to the new repository.
* Branch protection rules will need to be transferred to the new repository.
* Individual maintainers will be transferred to the new repository.
* GitHub teams will NOT be transferred to the new repository and will need to be re-created.
* Bazel CI configurations will need to be updated to point to the new repository.

Read more on [Transferring a repository](https://docs.github.com/en/repositories/creating-and-managing-repositories/transferring-a-repository) from GitHub documentation.

**Checklist:**

* [x] Obtain approval from the current project maintainers (@bazelbuild/go-maintainers).
* [x] Obtain approval from the bazel-contrib SIG (@alexeagle).
* [x] Initiate the transfer process on GitHub (@meteorcloudy).
* [x] Update Bazel CI settings and confirm presubmit & postsubmit work (@meteorcloudy).

**Comment by alexeagle** [comment]
Notes from SIG meeting: this transfer was unanimously approved by a thumbs-up vote.

**Comment by fmeum** [comment]
I approve for @bazelbuild/go-maintainers

**Comment by meteorcloudy** [comment]
Transfer is done, Bazel CI has been updated, let me know if there is any problem.
