### ISSUE TITLE
Allow default patches with go_deps

### ISSUE THREAD

**Issue by maffoo** [bazel-contrib/bazel-gazelle#1984]
The `go_deps` extension has a mechanism for having different default arguments for the underlying `go_repository` command. Currently there are overrides for `build_directives`, `build_extra_args`, and `build_file_generation`: https://github.com/bazel-contrib/bazel-gazelle/blob/28f43a444ecc4c0498928787ebb1e61fef08f6eb/internal/bzlmod/go_deps.bzl#L18-L20

The code is written in a way that we one could specify new defaults, but this is currently not done: https://github.com/bazel-contrib/bazel-gazelle/blob/master/internal/bzlmod/go_deps.bzl#L156-L160

The [go-tree-sitter](https://github.com/smacker/go-tree-sitter) library is used by the gazelle plugin for `rules_python` to parse python files during build file generation, and needs to be upgraded to a new version to support python 3.12 type parameter syntax (see https://github.com/bazelbuild/rules_python/issues/2396). However, the new version of `go-tree-sitter` does not build with gazelle because it has uplevel references to c header files. We tried to fix this by applying patches in the rules python repo (see https://github.com/bazelbuild/rules_python/pull/2413), but those overrides don't take effect when using using the rules python gazelle plugin because it is no longer the root module, so we would need the patches to be applied by bazel-gazelle.

**Comment by maffoo** [comment]
Note that if gazelle could handle uplevel file references when generating build files then patches for go-tree-sitter would not be necessary, though it may still be desirable to have a mechanism for applying default patches.

**Comment by fmeum** [comment]
I understand your use case, but maintaining patches to Go modules in this repo would certainly overstretch our responsibility budget. For example, we would need to have a plan for when the patch needs to change as new versions of the module are released.

Have you considered making `go-tree-sitter` a BCR module instead? Gazelle has special support for BCR modules that are also Go modules and avoids duplicating them in the dependency graph. You can refer to the `circl` module for an example.
