### ISSUE TITLE
bazel mod tidy logs a warning for the very thing it's about to fix

### ISSUE THREAD

**Issue by Buzz-Lightyear** [bazel-contrib/bazel-gazelle#1988]
### What version of gazelle are you using?
0.38.0

### What version of rules_go are you using?
0.49.0

### What version of Bazel are you using?
7.1.2

### Does this issue reproduce with the latest releases of all the above?
Yes

### What operating system and processor architecture are you using?
Darwin arm64

### What did you do?
Ran `bazel mod tidy` upon being prompted to do so

### What did you expect to see?
Updates to `MODULE.bazel` and no warnings

### What did you see instead?
`MODULE.bazel` did get updated but it still logged the same warning that it was about to fix

```
> bazel mod tidy
WARNING: ...: The module extension go_deps defined in @gazelle//:extensions.bzl reported incorrect imports of repositories via use_repo():

Not imported, but reported as direct dependencies by the extension (may cause the build to fail):
    com_github_hashicorp_go_cleanhttp, com_linkedin_golang_c2s_backend_api_c2s_backend_go_api, com_linkedin_golang_gurney_gurney, com_linkedin_golang_rubiks_api_rubiks_go_api, in_golnkd_nimbus_inventory_manager

Fix the use_repo calls by running 'bazel mod tidy'.
INFO: Updated use_repo calls for @gazelle//:extensions.bzl%go_deps
```

**Comment by fmeum** [comment]
This needs to be fixed in Bazel: https://github.com/bazelbuild/bazel/issues/24495
