### ISSUE TITLE
External version of buildtools do not work with bazel 8.0.0

### ISSUE THREAD

**Issue by mailto-jonas** [bazel-contrib/bazel-gazelle#1995]
### What version of gazelle are you using?
Version 0.40.0

### What version of rules_go are you using?
Version 0.51.0

### What version of Bazel are you using?
Version 8.0.0

### Does this issue reproduce with the latest releases of all the above?
Yes.

### What operating system and processor architecture are you using?
linux / x86_64

### What did you do?
Error occurs in loading phase when reading the "gazelle++go_deps+com_github_bazelbuild_buildtools/build/build_defs.bzl" file.

### What did you expect to see?
Build success

### What did you see instead?
`
ERROR: Traceback (most recent call last):
	File "/home/s0000461/.cache/bazel/_bazel_s0000461/bb9bd18d7a2c67075dcb87b08152b546/external/gazelle++go_deps+com_github_bazelbuild_buildtools/lang/BUILD.bazel", line 7, column 19, in <toplevel>
		genfile_check_test(
	File "/home/s0000461/.cache/bazel/_bazel_s0000461/bb9bd18d7a2c67075dcb87b08152b546/external/gazelle++go_deps+com_github_bazelbuild_buildtools/build/build_defs.bzl", line 133, column 11, in genfile_check_test
		native.sh_test(
Error: no native function or rule 'sh_test'

`

**Comment by fmeum** [comment]
Are you using Bazel 8 with default settings? Do you have a reproducer you can share?

The autoload functionality should ensure that `native.sh_test` keeps working as it did in Bazel 7, so this sounds more like a Bazel bug.

**Comment by mailto-jonas** [comment]
Turns out we had an erroneous setting from a previous bazel release candidate. Will close this issue. Thanks for input!
